services:
  registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_STORAGE_FILESYSTEM_MAXTHREADS: "100"
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
    restart: unless-stopped
    networks:
      - registry-net

networks:
  registry-net:
    driver: bridge 