apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pihole
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: "pihole"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"