---
# Common tasks for all hosts

# Remove warning messages from issue files
- name: Remove warning messages from issue files
  blockinfile:
    path: "{{ item }}"
    block: ""
    state: absent
  with_items:
    - /etc/issue
    - /etc/issue.net
  become: true 