---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10'
    ansible_ssh_retries: 3
    ansible_ssh_retry_delay: 5
    ned_uname: "{{ lookup('ansible.builtin.pipe', 'op item get homelab.ned --fields username') }}"
    ned_pass: "{{ lookup('ansible.builtin.pipe', 'op item get homelab.ned --fields password --reveal') }}"
    rod_uname: "{{ lookup('ansible.builtin.pipe', 'op item get homelab.rod --fields username') }}"
    rod_pass: "{{ lookup('ansible.builtin.pipe', 'op item get homelab.rod --fields password --reveal') }}"
    maude_uname: "{{ lookup('ansible.builtin.pipe', 'op item get homelab.maude --fields username') }}"
    maude_pass: "{{ lookup('ansible.builtin.pipe', 'op item get homelab.maude --fields password --reveal') }}"
    todd_uname: "{{ lookup('ansible.builtin.pipe', 'op item get homelab.todd --fields username') }}"
    todd_pass: "{{ lookup('ansible.builtin.pipe', 'op item get homelab.todd --fields password --reveal') }}"
    huey_uname: "{{ lookup('ansible.builtin.pipe', 'op item get homelab.huey --fields username') }}"
    huey_pass: "{{ lookup('ansible.builtin.pipe', 'op item get homelab.huey --fields password --reveal') }}"
  hosts:
    # huey:
    #   ansible_host: 192.168.0.17
    #   ansible_user: "{{ huey_uname }}"
    #   ansible_become_pass: "{{ huey_pass }}"
    #   ansible_connection: ssh
    maude:
      ansible_host: 192.168.0.82
      ansible_user: "{{ maude_uname }}"
      ansible_become_pass: "{{ maude_pass }}"
      ansible_connection: ssh
    rod:
      ansible_host: 192.168.0.83
      ansible_user: "{{ rod_uname }}"
      ansible_become_pass: "{{ rod_pass }}"
      ansible_connection: ssh
    ned:
      ansible_host: 192.168.0.84
      ansible_user: "{{ ned_uname }}"
      ansible_become_pass: "{{ ned_pass }}"
      ansible_connection: ssh
    todd:
      ansible_host: 192.168.0.85
      ansible_user: "{{ todd_uname }}"
      ansible_become_pass: "{{ todd_pass }}"
      ansible_connection: ssh