apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: pihole
  includeCRDs: false
  releaseName: pihole
  version: 6.12.0
  repo: https://mojo2600.github.io/pihole-kubernetes
  namespace: pihole
