apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: pihole
  includeCRDs: false
  releaseName: pihole
  version: 6.1.2
  repo: https://github.com/pi-hole/pi-hole
  namespace: pihole
  valuesInline:
    admin:
      password: "admin"
    service:
      type: ClusterIP
