---
- name: Install essential tools
  hosts: all
  become: yes
  
  tasks:
    - name: Install essential packages
      apt:
        name:
          # editing
          - vim
          # health
          - btop
          - htop
          - iotop
          - lm-sensors
          - glances
          - powertop
          - tlp
          # system
          - git
          - curl
          - wget
          - nfs-common
          - golang
        state: present
        update_cache: yes