---
- name: Install Helm
  hosts: all
  become: yes
  
  tasks:
    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm-3.sh
        mode: '0755'
        
    - name: Execute Helm installation script
      command: /tmp/get-helm-3.sh
      changed_when: true
      
    - name: Set KUBECONFIG for Helm (for root)
      lineinfile:
        path: /root/.bashrc
        line: 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml'
        state: present