---
- name: Install K8s Tools
  hosts: all
  become: yes
  
  tasks:
    - name: Install fzf
      block:
        - name: Install fzf package
          apt:
            name: fzf
            state: present
            update_cache: yes
            
        - name: Setup fzf keybindings and completions
          lineinfile:
            path: /home/{{ ansible_user }}/.bashrc
            line: '[ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash'
            state: present
            
        - name: Setup fzf completions
          lineinfile:
            path: /home/{{ ansible_user }}/.bashrc
            line: '[ -f /usr/share/doc/fzf/examples/completion.bash ] && source /usr/share/doc/fzf/examples/completion.bash'
            state: present
    
    - name: Install kubecolor
      block:
        - name: Install Go if not already installed
          apt:
            name: golang
            state: present
            update_cache: yes
          
        - name: Ensure GOPATH exists
          file:
            path: /home/{{ ansible_user }}/go
            state: directory
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0755'
          
        - name: Install kubecolor via go install
          shell: |
            su - {{ ansible_user }} -c "go install github.com/kubecolor/kubecolor@latest"
          
        - name: Ensure GOBIN is in PATH
          lineinfile:
            path: /home/{{ ansible_user }}/.bashrc
            line: 'export PATH=$PATH:/home/{{ ansible_user }}/go/bin'
            state: present
    
    - name: Setup kubectl alias for kubecolor
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: 'alias kubectl="kubecolor"'
        state: present