---
- name: Configure video output for Raspberry Pis
  hosts:
    - ned
    - maude
    - rod
    - todd
  become: yes

  tasks:
    - name: Check current kernel parameters
      command: cat /boot/firmware/cmdline.txt
      register: cmdline_check
      changed_when: false
      failed_when: false

    - name: Configure kernel parameters for video output
      copy:
        content: "console=serial0,115200 console=tty1 root=PARTUUID=662d1634-02 rootfstype=ext4 fsck.repair=yes rootwait quiet splash cgroup_enable=memory cgroup_memory=1\n"
        dest: /boot/firmware/cmdline.txt

    - name: Create config.txt if it doesn't exist
      file:
        path: /boot/firmware/config.txt
        state: touch
        mode: '0644'

    - name: Enable HDMI output
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: '^#?hdmi_force_hotplug='
        line: 'hdmi_force_hotplug=1'
        state: present

    - name: Set HDMI group
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: '^#?hdmi_group='
        line: 'hdmi_group=1'
        state: present

    - name: Set HDMI mode
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: '^#?hdmi_mode='
        line: 'hdmi_mode=4'
        state: present

    - name: Enable HDMI audio
      lineinfile:
        path: /boot/firmware/config.txt
        regexp: '^#?hdmi_drive='
        line: 'hdmi_drive=2'
        state: present

    - name: Reboot system to apply changes
      reboot:
        msg: "Reboot initiated by Ansible for video configuration"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30 