---
- name: Configure K3s for Insecure Registry
  hosts: all
  become: yes

  tasks:
    - name: Create K3s config directory
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: "0755"

    - name: Create K3s config file for insecure registry
      copy:
        dest: /etc/rancher/k3s/registries.yaml
        content: |
          configs:
            "192.168.0.17:5000":
              http: true
            "huey.local:5000":
              http: true
        mode: "0644"
      register: registry_config

    - name: Restart K3s service if config changed
      command: systemctl restart k3s
      when: registry_config.changed
      ignore_errors: yes

    - name: Restart K3s agent service if config changed
      command: systemctl restart k3s-agent
      when: registry_config.changed
      ignore_errors: yes
